version: '3'
services:
    zoneminder:
        container_name: Zoneminder
        image: doc4johnson/zoneminder:latest
        restart: unless-stopped
        ports:
            - 7373:443/tcp
            - 9000:9000/tcp
        environment:
            - TZ=Europe/Moscow
            - SHMEM=50%
            - PUID=99
            - PGID=100
        volumes:
            - /home/zoneminder/config:/config:rw
            - /home/zoneminder/data:/var/cache/zoneminder:rw
